import Head from 'next/head'
import React, {useEffect, useState} from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Data from '../data/data.json'


const inter = Inter({ subsets: ['latin'] })

function Home() {
  const [searchTerm, setSearchTerm] = useState("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
      <h1 className='h1'>European NBA Players</h1>
       <Image src="/img/european-players.png" width={400} height={250} className="img" />
       <div className='inputcontainer'>
            <input className='search' type="text" placeholder='search a nba players' 
             onChange={(e) => setSearchTerm(e.target.value)}
            />
       </div>
       <div className='dataContainer'>
               {
                Data.filter((val) => {
                  if(setSearchTerm==""){
                    return val;
                  } else if(val.title.toLocaleLowerCase().includes(searchTerm.toLocaleLowerCase())){
                      return val;
                  }
                }).map((val) => {
                     return (
                      <div className='data' key={val.id}>
                      <img src={val.image} className ="nbaplayers"/>
                      <h3 className="h3">{val.title}</h3>
                      <p className='p'>{val.Description}</p>
                 </div>
                     )
                })
               }
          </div>
      </div>

    </>
  )
}
export default Home
